-- Fondasi database dan keamanan panel admin Zonasi UMKM.
-- Jalankan melalui Supabase SQL Editor atau Supabase CLI.

create extension if not exists pgcrypto;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'Administrator',
  role text not null default 'admin'
    check (role in ('superadmin', 'admin', 'verifikator', 'viewer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.umkm (
  id bigint generated by default as identity primary key
    constraint umkm_id_nonnegative check (id >= 0),
  name text not null,
  product_type text not null default '',
  product_label text not null default '',
  brand text not null default '',
  owner text not null default '',
  address text not null default '',
  lat double precision,
  lng double precision,
  analysis_lat double precision,
  analysis_lng double precision,
  display_lat double precision,
  display_lng double precision,
  location_accuracy text not null default 'belum_terverifikasi'
    check (location_accuracy in ('tepat', 'perkiraan_kecamatan', 'belum_terverifikasi')),
  location_area text not null default '',
  is_active boolean not null default true,
  published boolean not null default true,
  verified_at timestamptz,
  -- Exact-location history must retain a valid verifier. Deleting an Auth user
  -- is therefore blocked until their verified rows are reassigned/downgraded.
  verified_by uuid references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint umkm_legacy_coordinates_pair
    check ((lat is null) = (lng is null)),
  constraint umkm_analysis_coordinates_pair
    check ((analysis_lat is null) = (analysis_lng is null)),
  constraint umkm_display_coordinates_pair
    check ((display_lat is null) = (display_lng is null)),
  constraint umkm_legacy_latitude_range
    check (lat is null or lat between -90 and 90),
  constraint umkm_legacy_longitude_range
    check (lng is null or lng between -180 and 180),
  constraint umkm_analysis_latitude_range
    check (analysis_lat is null or analysis_lat between -90 and 90),
  constraint umkm_analysis_longitude_range
    check (analysis_lng is null or analysis_lng between -180 and 180),
  constraint umkm_display_latitude_range
    check (display_lat is null or display_lat between -90 and 90),
  constraint umkm_display_longitude_range
    check (display_lng is null or display_lng between -180 and 180),
  constraint umkm_exact_location_metadata
    check (
      location_accuracy <> 'tepat'
      or (
        analysis_lat is not null
        and analysis_lng is not null
        and display_lat is not null
        and display_lng is not null
        and lat is not null
        and lng is not null
        and verified_at is not null
        and verified_by is not null
      )
    )
);

create table if not exists public.kmeans_runs (
  id uuid primary key default gen_random_uuid(),
  k_value integer not null check (k_value between 2 and 20),
  data_count integer not null check (data_count >= 0),
  iterations integer not null check (iterations >= 0),
  wcss double precision not null check (wcss >= 0),
  centroids jsonb not null default '[]'::jsonb,
  cluster_stats jsonb not null default '[]'::jsonb,
  parameters jsonb not null default '{}'::jsonb,
  dataset_hash text not null,
  input_snapshot jsonb not null default '[]'::jsonb,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  constraint kmeans_runs_dataset_hash_required
    check (dataset_hash is not null and btrim(dataset_hash) <> ''),
  constraint kmeans_runs_snapshot_matches_count
    check (
      jsonb_typeof(input_snapshot) = 'array'
      and jsonb_array_length(input_snapshot) = data_count
    )
);

create table if not exists public.import_batches (
  id uuid primary key default gen_random_uuid(),
  source_name text not null,
  total_rows integer not null default 0,
  valid_rows integer not null default 0,
  invalid_rows integer not null default 0,
  status text not null default 'completed'
    check (status in ('processing', 'completed', 'failed')),
  error_message text,
  imported_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  table_name text not null,
  record_id text,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  old_data jsonb,
  new_data jsonb,
  actor_id uuid,
  actor_email text,
  created_at timestamptz not null default now()
);

-- Keep this foundation migration safe if it is reapplied to a database that
-- was initialized using an earlier draft of the same schema.
alter table public.kmeans_runs
  add column if not exists dataset_hash text;
alter table public.kmeans_runs
  add column if not exists input_snapshot jsonb not null default '[]'::jsonb;
alter table public.import_batches
  add column if not exists error_message text;

-- Align an installation created from the earlier draft with the exact-location
-- invariant above. ON DELETE SET NULL would otherwise violate the metadata
-- CHECK whenever a verifier account is deleted.
alter table public.umkm
  drop constraint if exists umkm_verified_by_fkey;
alter table public.umkm
  add constraint umkm_verified_by_fkey
  foreign key (verified_by) references auth.users(id) on delete restrict;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_id_nonnegative'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_id_nonnegative check (id >= 0) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_legacy_coordinates_pair'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_legacy_coordinates_pair
      check ((lat is null) = (lng is null)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_analysis_coordinates_pair'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_analysis_coordinates_pair
      check ((analysis_lat is null) = (analysis_lng is null)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_display_coordinates_pair'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_display_coordinates_pair
      check ((display_lat is null) = (display_lng is null)) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_legacy_latitude_range'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_legacy_latitude_range
      check (lat is null or lat between -90 and 90) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_legacy_longitude_range'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_legacy_longitude_range
      check (lng is null or lng between -180 and 180) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_analysis_latitude_range'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_analysis_latitude_range
      check (analysis_lat is null or analysis_lat between -90 and 90) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_analysis_longitude_range'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_analysis_longitude_range
      check (analysis_lng is null or analysis_lng between -180 and 180) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_display_latitude_range'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_display_latitude_range
      check (display_lat is null or display_lat between -90 and 90) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_display_longitude_range'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_display_longitude_range
      check (display_lng is null or display_lng between -180 and 180) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'umkm_exact_location_metadata'
      and conrelid = 'public.umkm'::regclass
  ) then
    alter table public.umkm
      add constraint umkm_exact_location_metadata
      check (
        location_accuracy <> 'tepat'
        or (
          analysis_lat is not null
          and analysis_lng is not null
          and display_lat is not null
          and display_lng is not null
          and lat is not null
          and lng is not null
          and verified_at is not null
          and verified_by is not null
        )
      ) not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'kmeans_runs_dataset_hash_required'
      and conrelid = 'public.kmeans_runs'::regclass
  ) then
    alter table public.kmeans_runs
      add constraint kmeans_runs_dataset_hash_required
      check (dataset_hash is not null and btrim(dataset_hash) <> '') not valid;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'kmeans_runs_snapshot_matches_count'
      and conrelid = 'public.kmeans_runs'::regclass
  ) then
    alter table public.kmeans_runs
      add constraint kmeans_runs_snapshot_matches_count
      check (
        jsonb_typeof(input_snapshot) = 'array'
        and jsonb_array_length(input_snapshot) = data_count
      ) not valid;
  end if;
end;
$$;

create index if not exists umkm_active_published_idx
  on public.umkm (is_active, published);
create index if not exists umkm_location_accuracy_idx
  on public.umkm (location_accuracy);
create index if not exists umkm_product_type_idx
  on public.umkm (product_type);
create index if not exists umkm_location_area_idx
  on public.umkm (location_area);
create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);
create index if not exists kmeans_runs_created_at_idx
  on public.kmeans_runs (created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = (select auth.uid())
      and is_active = true
      and role in ('superadmin', 'admin', 'verifikator', 'viewer')
  );
$$;

create or replace function public.can_manage_umkm()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = (select auth.uid())
      and is_active = true
      and role in ('superadmin', 'admin')
  );
$$;

create or replace function public.can_verify_umkm()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = (select auth.uid())
      and is_active = true
      and role in ('superadmin', 'admin', 'verifikator')
  );
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.normalize_umkm_location()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  verification_flow boolean :=
    coalesce(current_setting('app.verify_umkm_location', true), 'off') = 'on';
begin
  -- A manager may still edit ordinary business metadata on an exact record,
  -- but exact status/location/verification metadata can only be touched by the
  -- guarded verify_umkm_location() RPC below.
  if tg_op = 'INSERT' then
    if new.location_accuracy = 'tepat' and not verification_flow then
      raise exception
        'Status lokasi tepat hanya dapat ditetapkan melalui verifikasi lokasi.'
        using errcode = '42501';
    end if;
  elsif not verification_flow
    and (old.location_accuracy = 'tepat' or new.location_accuracy = 'tepat')
    and (
      old.location_accuracy is distinct from new.location_accuracy
      or old.analysis_lat is distinct from new.analysis_lat
      or old.analysis_lng is distinct from new.analysis_lng
      or old.display_lat is distinct from new.display_lat
      or old.display_lng is distinct from new.display_lng
      or old.lat is distinct from new.lat
      or old.lng is distinct from new.lng
      or old.location_area is distinct from new.location_area
      or old.verified_at is distinct from new.verified_at
      or old.verified_by is distinct from new.verified_by
    ) then
    raise exception
      'Status, koordinat, wilayah, dan metadata lokasi tepat hanya dapat diubah melalui verifikasi lokasi.'
      using errcode = '42501';
  end if;

  if new.location_accuracy = 'tepat' then
    if verification_flow then
      -- Exact locations use one canonical coordinate for analysis, display,
      -- and legacy clients. The table constraint rejects an incomplete pair.
      new.display_lat := new.analysis_lat;
      new.display_lng := new.analysis_lng;
      new.lat := new.analysis_lat;
      new.lng := new.analysis_lng;
      new.verified_at := now();
      new.verified_by := coalesce(auth.uid(), new.verified_by);
    elsif tg_op = 'UPDATE' then
      -- Preserve the original verification evidence during ordinary edits to
      -- fields such as name, category, owner, publication, or active status.
      new.location_accuracy := old.location_accuracy;
      new.analysis_lat := old.analysis_lat;
      new.analysis_lng := old.analysis_lng;
      new.display_lat := old.display_lat;
      new.display_lng := old.display_lng;
      new.lat := old.lat;
      new.lng := old.lng;
      new.location_area := old.location_area;
      new.verified_at := old.verified_at;
      new.verified_by := old.verified_by;
    end if;
  else
    -- Verification metadata must never survive after a location is downgraded.
    new.verified_at := null;
    new.verified_by := null;
  end if;

  return new;
end;
$$;

create or replace function public.audit_umkm_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  affected_id text;
begin
  affected_id := coalesce(new.id, old.id)::text;
  insert into public.audit_logs (
    table_name, record_id, action, old_data, new_data, actor_id, actor_email
  ) values (
    tg_table_name,
    affected_id,
    tg_op,
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end,
    (select auth.uid()),
    (select auth.jwt() ->> 'email')
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists admin_profiles_set_updated_at on public.admin_profiles;
create trigger admin_profiles_set_updated_at
before update on public.admin_profiles
for each row execute function public.set_updated_at();

-- Remove trigger/function names used by an earlier draft before installing the
-- canonical normalizer and explicit sequence synchronization in the import RPC.
drop trigger if exists umkm_normalize_verification on public.umkm;
drop trigger if exists umkm_sync_id_sequence on public.umkm;
drop function if exists public.normalize_umkm_verification();
drop function if exists public.sync_umkm_id_sequence();

drop trigger if exists umkm_normalize_location on public.umkm;
create trigger umkm_normalize_location
before insert or update on public.umkm
for each row execute function public.normalize_umkm_location();

drop trigger if exists umkm_set_updated_at on public.umkm;
create trigger umkm_set_updated_at
before update on public.umkm
for each row execute function public.set_updated_at();

drop trigger if exists umkm_audit_changes on public.umkm;
create trigger umkm_audit_changes
after insert or update or delete on public.umkm
for each row execute function public.audit_umkm_change();

alter table public.admin_profiles enable row level security;
alter table public.umkm enable row level security;
alter table public.kmeans_runs enable row level security;
alter table public.import_batches enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.admin_profiles from anon, authenticated;
revoke all on table public.umkm from anon, authenticated;
revoke all on table public.kmeans_runs from anon, authenticated;
revoke all on table public.import_batches from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;

grant select on table public.admin_profiles to authenticated;
grant select on table public.umkm to anon, authenticated;
grant insert, update, delete on table public.umkm to authenticated;
grant select, insert on table public.kmeans_runs to authenticated;
grant select on table public.import_batches to authenticated;
grant select on table public.audit_logs to authenticated;
grant usage, select on sequence public.umkm_id_seq to authenticated;

revoke all on function public.is_admin() from public;
revoke all on function public.can_manage_umkm() from public;
revoke all on function public.can_verify_umkm() from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.can_manage_umkm() to authenticated;
grant execute on function public.can_verify_umkm() to authenticated;

drop policy if exists admin_profiles_read_self_or_admin on public.admin_profiles;
create policy admin_profiles_read_self_or_admin
on public.admin_profiles for select to authenticated
using (
  (select auth.uid()) = user_id
  or (select public.can_manage_umkm())
);

drop policy if exists umkm_public_read on public.umkm;
create policy umkm_public_read
on public.umkm for select to anon, authenticated
using (is_active = true and published = true);

drop policy if exists umkm_admin_read on public.umkm;
create policy umkm_admin_read
on public.umkm for select to authenticated
using ((select public.is_admin()));

drop policy if exists umkm_admin_insert on public.umkm;
create policy umkm_admin_insert
on public.umkm for insert to authenticated
with check ((select public.can_manage_umkm()));

drop policy if exists umkm_admin_update on public.umkm;
create policy umkm_admin_update
on public.umkm for update to authenticated
using ((select public.can_manage_umkm()))
with check ((select public.can_manage_umkm()));

drop policy if exists umkm_admin_delete on public.umkm;
create policy umkm_admin_delete
on public.umkm for delete to authenticated
using ((select public.can_manage_umkm()));

drop policy if exists kmeans_runs_admin_read on public.kmeans_runs;
create policy kmeans_runs_admin_read
on public.kmeans_runs for select to authenticated
using ((select public.is_admin()));

drop policy if exists kmeans_runs_admin_insert on public.kmeans_runs;
create policy kmeans_runs_admin_insert
on public.kmeans_runs for insert to authenticated
with check (
  (select public.can_manage_umkm())
  and created_by = (select auth.uid())
);

drop policy if exists import_batches_admin_read on public.import_batches;
create policy import_batches_admin_read
on public.import_batches for select to authenticated
using ((select public.is_admin()));

-- Batch rows are written only by import_umkm_batch(), never directly by a
-- browser client. Remove the policy from an earlier draft if it exists.
drop policy if exists import_batches_admin_insert on public.import_batches;

drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read
on public.audit_logs for select to authenticated
using ((select public.is_admin()));

create or replace function public.verify_umkm_location(
  p_umkm_id bigint,
  p_lat double precision,
  p_lng double precision,
  p_location_accuracy text,
  p_location_area text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  verified_business public.umkm%rowtype;
  previous_verification_context text;
  business_was_found boolean := false;
begin
  if not public.can_verify_umkm() then
    raise exception 'Akun tidak memiliki izin untuk memverifikasi lokasi.'
      using errcode = '42501';
  end if;

  if p_lat is null or p_lat < -90 or p_lat > 90 then
    raise exception 'Latitude harus berada pada rentang -90 sampai 90.'
      using errcode = '22023';
  end if;

  if p_lng is null or p_lng < -180 or p_lng > 180 then
    raise exception 'Longitude harus berada pada rentang -180 sampai 180.'
      using errcode = '22023';
  end if;

  if p_location_accuracy not in ('tepat', 'perkiraan_kecamatan') then
    raise exception 'Status verifikasi lokasi tidak valid.'
      using errcode = '22023';
  end if;

  previous_verification_context :=
    current_setting('app.verify_umkm_location', true);
  perform set_config('app.verify_umkm_location', 'on', true);

  begin
    update public.umkm
    set analysis_lat = p_lat,
        analysis_lng = p_lng,
        display_lat = p_lat,
        display_lng = p_lng,
        lat = p_lat,
        lng = p_lng,
        location_accuracy = p_location_accuracy,
        location_area = coalesce(p_location_area, '')
    where id = p_umkm_id
    returning * into verified_business;

    business_was_found := found;
  exception
    when others then
      perform set_config(
        'app.verify_umkm_location',
        coalesce(nullif(previous_verification_context, ''), 'off'),
        true
      );
      raise;
  end;

  perform set_config(
    'app.verify_umkm_location',
    coalesce(nullif(previous_verification_context, ''), 'off'),
    true
  );

  if not business_was_found then
    raise exception 'Data UMKM dengan ID % tidak ditemukan.', p_umkm_id
      using errcode = 'P0002';
  end if;

  return to_jsonb(verified_business);
end;
$$;

revoke all on function public.verify_umkm_location(
  bigint, double precision, double precision, text, text
) from public;
grant execute on function public.verify_umkm_location(
  bigint, double precision, double precision, text, text
) to authenticated;

create or replace function public.import_umkm_batch(
  p_source_name text,
  p_records jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  batch public.import_batches%rowtype;
  item jsonb;
  total_count integer := case
    when jsonb_typeof(p_records) = 'array' then jsonb_array_length(p_records)
    else 0
  end;
  current_row integer := 0;
  imported_id bigint;
  imported_name text;
  imported_product_type text;
  imported_product_label text;
  imported_brand text;
  imported_owner text;
  imported_address text;
  imported_analysis_lat double precision;
  imported_analysis_lng double precision;
  imported_display_lat double precision;
  imported_display_lng double precision;
  imported_accuracy text;
  imported_area text;
  imported_is_active boolean;
  imported_published boolean;
begin
  if not public.can_manage_umkm() then
    raise exception 'Akun tidak memiliki izin untuk mengimpor data UMKM.'
      using errcode = '42501';
  end if;

  insert into public.import_batches (
    source_name,
    total_rows,
    valid_rows,
    invalid_rows,
    status,
    error_message,
    imported_by
  ) values (
    coalesce(nullif(btrim(p_source_name), ''), 'Impor tanpa nama'),
    total_count,
    0,
    0,
    'processing',
    null,
    auth.uid()
  ) returning * into batch;

  -- A PL/pgSQL block with EXCEPTION is a subtransaction. If any row fails,
  -- every UMKM mutation below is rolled back, while the batch row created
  -- above remains available to be marked as failed.
  begin
    if p_records is null or jsonb_typeof(p_records) <> 'array' then
      raise exception 'Payload records harus berupa array JSON.'
        using errcode = '22023';
    end if;

    -- Serialize imports and direct writes while explicit legacy IDs are being
    -- loaded and the identity sequence is synchronized.
    lock table public.umkm in share row exclusive mode;

    for item in
      select value from jsonb_array_elements(p_records)
    loop
      current_row := current_row + 1;

      if jsonb_typeof(item) <> 'object' then
        raise exception 'Baris % bukan objek JSON.', current_row
          using errcode = '22023';
      end if;

      imported_id := nullif(item ->> 'id', '')::bigint;
      imported_name := coalesce(
        nullif(btrim(item ->> 'name'), ''),
        'Data UMKM'
      );
      imported_product_type := coalesce(btrim(item ->> 'product_type'), '');
      imported_product_label := coalesce(btrim(item ->> 'product_label'), '');
      imported_brand := coalesce(btrim(item ->> 'brand'), '');
      imported_owner := coalesce(btrim(item ->> 'owner'), '');
      imported_address := coalesce(btrim(item ->> 'address'), '');
      imported_analysis_lat := coalesce(
        nullif(item ->> 'analysis_lat', '')::double precision,
        nullif(item ->> 'lat', '')::double precision
      );
      imported_analysis_lng := coalesce(
        nullif(item ->> 'analysis_lng', '')::double precision,
        nullif(item ->> 'lng', '')::double precision
      );
      imported_display_lat := coalesce(
        nullif(item ->> 'display_lat', '')::double precision,
        nullif(item ->> 'lat', '')::double precision,
        imported_analysis_lat
      );
      imported_display_lng := coalesce(
        nullif(item ->> 'display_lng', '')::double precision,
        nullif(item ->> 'lng', '')::double precision,
        imported_analysis_lng
      );
      imported_accuracy := coalesce(
        nullif(btrim(item ->> 'location_accuracy'), ''),
        'belum_terverifikasi'
      );
      if imported_accuracy = 'tepat' then
        raise exception
          'Status lokasi tepat tidak boleh diimpor; tetapkan melalui fitur verifikasi lokasi.'
          using errcode = '42501';
      end if;
      imported_area := coalesce(btrim(item ->> 'location_area'), '');
      imported_is_active := coalesce(
        nullif(item ->> 'is_active', '')::boolean,
        true
      );
      imported_published := coalesce(
        nullif(item ->> 'published', '')::boolean,
        true
      );

      if imported_id is null then
        insert into public.umkm (
          name, product_type, product_label, brand, owner, address,
          lat, lng, analysis_lat, analysis_lng, display_lat, display_lng,
          location_accuracy, location_area, is_active, published
        ) values (
          imported_name, imported_product_type, imported_product_label,
          imported_brand, imported_owner, imported_address,
          imported_display_lat, imported_display_lng,
          imported_analysis_lat, imported_analysis_lng,
          imported_display_lat, imported_display_lng,
          imported_accuracy, imported_area,
          imported_is_active, imported_published
        );
      else
        insert into public.umkm (
          id, name, product_type, product_label, brand, owner, address,
          lat, lng, analysis_lat, analysis_lng, display_lat, display_lng,
          location_accuracy, location_area, is_active, published
        ) values (
          imported_id, imported_name, imported_product_type,
          imported_product_label, imported_brand, imported_owner,
          imported_address, imported_display_lat, imported_display_lng,
          imported_analysis_lat, imported_analysis_lng,
          imported_display_lat, imported_display_lng,
          imported_accuracy, imported_area,
          imported_is_active, imported_published
        )
        on conflict (id) do update
        set name = excluded.name,
            product_type = excluded.product_type,
            product_label = excluded.product_label,
            brand = excluded.brand,
            owner = excluded.owner,
            address = excluded.address,
            lat = excluded.lat,
            lng = excluded.lng,
            analysis_lat = excluded.analysis_lat,
            analysis_lng = excluded.analysis_lng,
            display_lat = excluded.display_lat,
            display_lng = excluded.display_lng,
            location_accuracy = excluded.location_accuracy,
            location_area = excluded.location_area,
            is_active = excluded.is_active,
            published = excluded.published;
      end if;
    end loop;

    -- Explicit IDs do not advance a PostgreSQL identity sequence. Set it to
    -- the first unused value so the next regular insert cannot collide.
    perform setval(
      pg_get_serial_sequence('public.umkm', 'id'),
      greatest(
        coalesce((select max(id) from public.umkm), 0) + 1,
        (
          select last_value + case when is_called then 1 else 0 end
          from public.umkm_id_seq
        ),
        1
      ),
      false
    );
  exception
    when others then
      update public.import_batches
      set status = 'failed',
          valid_rows = 0,
          invalid_rows = total_count,
          error_message = left(
            format('Baris %s: %s', greatest(current_row, 1), sqlerrm),
            4000
          )
      where id = batch.id
      returning * into batch;

      return jsonb_build_object(
        'success', false,
        'message', batch.error_message,
        'batch_id', batch.id,
        'status', batch.status,
        'total_rows', batch.total_rows,
        'valid_rows', batch.valid_rows,
        'invalid_rows', batch.invalid_rows
      );
  end;

  update public.import_batches
  set status = 'completed',
      valid_rows = total_count,
      invalid_rows = 0,
      error_message = null
  where id = batch.id
  returning * into batch;

  return jsonb_build_object(
    'success', true,
    'message', format('%s data berhasil diimpor.', total_count),
    'batch_id', batch.id,
    'status', batch.status,
    'total_rows', batch.total_rows,
    'valid_rows', batch.valid_rows,
    'invalid_rows', batch.invalid_rows
  );
end;
$$;

revoke all on function public.import_umkm_batch(text, jsonb) from public;
grant execute on function public.import_umkm_batch(text, jsonb) to authenticated;

-- Policies from the earlier draft no longer depend on can_edit_umkm(), so the
-- overly broad helper can be removed safely when upgrading an existing setup.
drop function if exists public.can_edit_umkm();

-- Also repair a sequence immediately when this migration is applied after an
-- earlier manual seed. false means the next nextval() returns max(id) + 1.
select setval(
  pg_get_serial_sequence('public.umkm', 'id'),
  greatest(
    coalesce((select max(id) from public.umkm), 0) + 1,
    (
      select last_value + case when is_called then 1 else 0 end
      from public.umkm_id_seq
    ),
    1
  ),
  false
);

-- Setelah membuat akun admin melalui Authentication > Users, jalankan:
-- insert into public.admin_profiles (user_id, full_name, role)
-- select id, 'Nama Administrator', 'superadmin'
-- from auth.users
-- where email = 'email-admin@contoh.id';
